# permissions for end users to edit appinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: appinstance-editor-role
rules:
- apiGroups:
  - mygroup.mydomain.com
  resources:
  - appinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.mydomain.com
  resources:
  - appinstances/status
  verbs:
  - get
